<?php

// Janrain Random User Generator (J-RUG)
// tsmith@janrain.com

session_start();

include 'includes/functions/sendCurlRequest.php';
include 'includes/functions/errorChecking.php';
include "getTotalUserCountInDB.php";

if (empty($_POST["serverID"])) { 
    // if the value for serverID is empty then the user has entered in values
    // manually for serverURL, client_id, client_server
    
    $apid_uri = $_POST["serverURL"];    
    $client_id = $_POST["client_id"];
    $client_secret = $_POST["client_secret"];
    
    $thisArray["serverName"] = str_replace("https://", "", $apid_uri);
    $thisArray["serverName"] = str_replace(".janraincapture.com", "", $thisArray["serverName"]);

}
else {
    $serverID = $_POST["serverID"];

    $apid_uri = $_SESSION['listOfServers'][$serverID]["apid_uri"];
        
    $client_id = $_SESSION['listOfServers'][$serverID]["client_id"];
    
    $client_secret = $_SESSION['listOfServers'][$serverID]["client_secret"];
    
    $thisArray["serverName"] = $serverID;

}

$captureServer = rtrim($apid_uri, '/') . '/'; // adds a final slash

$params["client_id"] = $client_id;

$params["client_secret"] = $client_secret;

$jsonResponse = sendCurlRequest ("entityType", $params, $captureServer);
    
$jsonArray = json_decode($jsonResponse, true);

$output = "<div class='divTable'>";

/************** Check to see if Client_id and _secret work *********/
    
$output .= establishErrorCategory( $thisArray["serverName"] . " credentials OK?");
    
if ($jsonArray["stat"] == "ok") { 
    $output .= keepGoing();
    
    $_SESSION["captureServer"] = $captureServer;
    $_SESSION['client_id'] = $client_id;
    $_SESSION['client_secret'] = $client_secret;
    
}
else { exitWithOutput($output); }
    
/***** Check to see if schema has isAutogeneratedUser field *********/

$output .= establishErrorCategory( $thisArray["serverName"] . " schema OK?");
    
if (strpos($jsonResponse, "isAutogeneratedUser") === FALSE) {
    exitWithOutput($output, "No isAutogeneratedUser field in schema."); 
}
else { 
    $output .= keepGoing();

    $thisArray["schemaStatus"] = "OK";

    /************* get total user count *****************/

    $params["type_name"] = "user";

    $thisArray["totalCount"] = getTotalUserCountInDB($params, $captureServer);

    /************* get autogen user count *******************/

    $thisArray["autogenCount"] = getTotalUserCountInDB($params, $captureServer, "autogen");
}

$output .= "</div>";

$thisArray["html"] = $output;

echo json_encode($thisArray);

exit;

?>