<?php

// assumes client_id, client_secret, and user_type in $params
function getTotalUserCountInDB ($params, $captureServer, $realOrAutoUser = "real") {

    if ($realOrAutoUser == "autogen") { $params["filter"] = "isAutogeneratedUser = 'true'"; }

    $jsonResponse = sendCurlRequest("entity.count", $params, $captureServer);

    $jsonArray = json_decode($jsonResponse, true);
    
    if ($jsonArray["stat"] == "ok") {
        return $jsonArray["total_count"];
    }
    else { return $jsonResponse; }

}

