<?php

// Janrain Random User Generator (J-RUG)
// tsmith@janrain.com

session_start();

include 'includes/functions/sendCurlRequest.php';
include 'includes/functions/errorChecking.php';

$captureServer = $_SESSION["captureServer"];
$params["client_id"] = $_SESSION['client_id'];
$params["client_secret"] = $_SESSION['client_secret'];
$params["type_name"] = "user";

$thisArray["name"] = "isAutogeneratedUser";
$thisArray["type"] = "boolean";

$params["attr_def"] = json_encode($thisArray);

$jsonResponse = sendCurlRequest ("entityType.addAttribute", $params, $captureServer);
    
$jsonArray = json_decode($jsonResponse, true);

$output = "<div class='divTable'>";
    
$output .= establishErrorCategory( $captureServer . " schema OK?");
    
if ($jsonArray["stat"] == "ok") { 
    $output .= keepGoing();
    
    $thisArray["schemaStatus"] = "OK";
    
}
else { exitWithOutput($output, $jsonResponse); }

$output .= "</div>";

$thisArray["html"] = $output;

echo json_encode($thisArray);

exit;

?>