<?php

function exitWithOutput($output, $message = "No") {
    
    $output .= "<div class = 'divCellNotOK'>" . $message . "</div>";
    
    $output .= "</div></div></div>"; # cell / row / table
    
    $thisArray["html"] = $output;
    
    // This is a hack.
    if ($message == "No isAutogeneratedUser field in schema.") {
        $thisArray["schemaStatus"] = "incomplete";
    }

    echo json_encode($thisArray);

    exit;
    
}

function keepGoing($message = "Yes") {
    return "<div class = 'divCellOK'>$message</div></div>";
}

function establishErrorCategory($message) {
    $output = "<div class='divRow'>";

    $output .= "<div class= 'divCell'>$message</div>";
    
    return $output;
}

